export const FETCH_RESTAURANTS_BEGIN = 'FETCH_RESTAURANTS_BEGIN';
export const FETCH_RESTAURANTS_SUCCESS = 'FETCH_RESTAURANTS_SUCCESS';
export const FETCH_RESTAURANTS_FAILURE = 'FETCH_RESTAURANTS_FAILURE';
export const SET_USER_TYPE_ADMIN = 'SET_USER_TYPE_ADMIN';
export const SET_USER_TYPE_DUMMY = 'SET_USER_TYPE_DUMMY';